### ISSUE TITLE
Not able to download the go modules to get started

### ISSUE THREAD

**Issue by arcAman07** [utreexo/utreexod#21]
The command doesn't work properly and is not downloading the go modules required to start working on the project => $ go install -v . ./cmd/...
![image](https://user-images.githubusercontent.com/76823502/156788063-2791692b-ca73-4ebe-8b4e-1753928c7cb5.png)
I am facing this error for that. 
$ GO111MODULE=on go install ./...
Used this command and all the go modules were properly downloaded to get it started.
Also maybe we can update the documentation , also it can be improved in terms of getting started. 
Let me know if it would need a PR, would love to work on that as an initial contribution.

**Comment by kcalvinalvin** [comment]
Hey thanks for the issue!

Could you tell me which version of Go you're on? Go 1.17 should ignore `GO111MODULE` so it shouldn't matter.

Though I've not built the binary on Windows so if you got it to work, it'd be nice to include a windows section on the readme.

**Comment by kcalvinalvin** [comment]
closing due to no response
