### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Davidson-Souza** [utreexo/utreexod#63]
While synchronizing with testnet or mainnet I got a peak memory usage of 8GB, using the default config. I'm not familiar with Go profiling utilities, but I can try getting more data if needed. Here's a print of an utreexod running on testnet, taking 8GB + some swap.
My computer is an AMD Ryzen 5 2500U, 12GB of RAM. go version go1.20.3 linux/amd64
![image](https://user-images.githubusercontent.com/40968167/232237232-f2c1a0d5-4585-48ea-8055-427b017869a2.png)

**Comment by jaonoctus** [comment]
same here

![image](https://user-images.githubusercontent.com/7918067/232258692-6eac4585-001c-480f-b109-35ce4e4427d9.png)

**Comment by Davidson-Souza** [comment]
After some testing, looks like the problem is with utreexo state. I believe the problem here is the map of txids to utreexo leaves. 
The memory usage ramps up while this message is on the terminal:  `Initializing Utreexo state from [scrubbed]`

**Comment by kcalvinalvin** [comment]
> After some testing, looks like the problem is with utreexo state. I believe the problem here is the map of txids to utreexo leaves.
> The memory usage ramps up while this message is on the terminal: `Initializing Utreexo state from [scrubbed]`

Yeah this is one of the problems.

The other is that the utxocache will take up a huge amount of ram. This is fixed in
